FROM node:16.20.2-bookworm

ENV NODE_ENV=development

WORKDIR /misskey

RUN apt-get update
RUN apt-get install -y build-essential \
                       ffmpeg \
                       wget \
                       postgresql-client

RUN corepack enable pnpm

CMD ["/misskey/docker-entrypoint.sh"]
