FROM node:22.22.3-bookworm

ENV NODE_ENV=development
ENV COREPACK_DEFAULT_TO_LATEST=0

WORKDIR /misskey

RUN apt-get update
RUN apt-get install -y build-essential \
                       ffmpeg \
                       wget \
                       curl \
                       postgresql-client

RUN corepack enable pnpm

CMD ["/misskey/docker-entrypoint.sh"]
